name: Rebuild README
on:
  workflow_dispatch:
    inputs:
      from:
        description: "The person that sent the message"
        required: true
      message:
        description: "A message to add to the README"
        required: true

jobs:
  build_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Install any dependencies
        run: npm install
      - name: Build a new README
        run: npm run build
        env:
          FROM: ${{ github.event.inputs.from }}
          MESSAGE: ${{ github.event.inputs.message }}
      - name: Commit and push if changed
        run: |-
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "🤖 Updated README.md" || exit 0
          git push
